### PR TITLE
added typescript support

### PR DESCRIPTION
**Pull request by chrismatix**
Added
- typescript support
- changelog
- contribution guideline

### CODE REVIEW

**Comment by chrismatix** [comment]
@makinde and @dvideby0 please take a look. A few things to note:

- It's time consuming to maintain typescript along side with eslint, so I went for tslint. For a bigger project eslint outperforms tslint in my opinion, but here it should be ok.
- I had to change a lot more than I liked and I know that the typescript defs can looked redundant at first, but it's great at preventing errors long term.
- I also added an opinionated changelog and contributing guide.

That's it for now, maybe I forgot something.

**Comment by makinde** [comment]
Thanks for taking a pass and showing what this would look like.

I'm personally in favor of sticking with vanilla JS here. For me (and I imagine anyone not used to typescript) this adds a lot of complexity and overhead to the system. For this codebase, I'm not sure we're getting the true value of typescript to make up for the costs. The vast majority of the type definitions are `:any` with just a couple optional params. The type definitions for the schema seem to be replicating what mongoose does.

I'm super new to these libraries, but perhaps flow would be a useful alternative here. From what I can see, it can be incrementally introduced, and can be used at just the function level, where I think it'll be most useful for us. That would allow you to target the areas of code that you're most concerned about at the start. Additionally, it think we could keep using eslint. Overall, it's prob a smaller change. My guess is that it's probably most valuable to type hint the parameters that aren't `schema`, `doc`, or other clearly mongoose params.

I do like the changeling and contribution guide. Perhaps you can break those out into their own diff?

**Comment by chrismatix** [comment]
@makinde will do so. Then we need to create a new PR for the polyfills and (potentially) flow. We could also make TS incremental, but I get your point. Sort of what I was thinking. Our codebase is a lot bigger and maybe it does need scale to really make sense. So agreed.

**Comment by brysgo** [comment]
@makinde - I think the purpose of typescript here was more to act as an alternative to babel than flow. While it is true that typescript adds a type system, it also maintains pretty close compatibility with the latest ECMAScript.

@xChrisPx - I don't see the harm in adding typescript, while I get curmudgeony about being forced to use types, I can just `any` everything and make the compiler shut up.

**Comment by chrismatix** [comment]
I really don't mind either way, but I will leave this open until we have a babel alternative that adds polyfills.

**Comment by makinde** [comment]
What's the root goal here? 

Is it to make the library with on a lower version of node? Is anyone here running node <8? If so, just add Babel.

Is it to introduce types, which I don't think as much value yet? Then set up for and add it just to the parts you think it's valuable on.

These can be done independent of one another.

With the info I see, it doesnt seem like either gets us closer to 2.0.0 or makes using the library easier.

**Pull request closed without merging**
